[project]
name = "python-toy"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jonathan Hall", email = "jonathan@jhall.io" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
python-toy = "python_toy:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
